# Generated by Django 4.2.7 on 2023-11-18 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Muzyk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('pseudonim', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=100)),
                ('datawydania', models.DateField()),
                ('liczbagwiazdek', models.IntegerField()),
                ('artysta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymViewApp.muzyk')),
            ],
        ),
    ]
