# Generated by Django 4.2.7 on 2023-12-03 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymViewApp', '0001_my_custom_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingexercise',
            name='number_of_replication',
        ),
        migrations.RemoveField(
            model_name='trainingexercise',
            name='number_of_series',
        ),
        migrations.RemoveField(
            model_name='trainingexercise',
            name='weight',
        ),
    ]
