# Generated by Django 5.0.1 on 2024-01-10 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymViewApp', '0002_remove_trainingexercise_number_of_replication_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='trainee',
        ),
        migrations.RemoveField(
            model_name='savedtraining',
            name='owner',
        ),
        migrations.AlterField(
            model_name='weight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='week',
            name='exercise',
        ),
        migrations.AddField(
            model_name='exercise',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedtraining',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='training',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ExerciseWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymViewApp.exercise')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymViewApp.week')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='weeks',
            field=models.ManyToManyField(related_name='exercise_weeks', through='gymViewApp.ExerciseWeek', to='gymViewApp.week'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
