# Generated by Django 4.2.7 on 2023-11-18 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymViewApp', '0002_exercises_savedtrainings_training_user_week_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weight',
            name='user',
        ),
        migrations.AddField(
            model_name='weight',
            name='exercises',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gymViewApp.exercises'),
        ),
    ]
