# Generated by Django 4.2.7 on 2023-11-20 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymViewApp', '0004_alter_training_date_alter_week_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercises',
            name='weeks',
        ),
    ]
