# Generated by Django 4.2.7 on 2023-11-20 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymViewApp', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weight',
            name='exercises',
        ),
        migrations.AddField(
            model_name='weight',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gymViewApp.user'),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='users',
            field=models.ManyToManyField(related_name='exercises', to='gymViewApp.user'),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='weeks',
            field=models.ManyToManyField(blank=True, null=True, related_name='exercise_weeks', to='gymViewApp.week'),
        ),
    ]
