# Generated by Django 4.2.7 on 2023-11-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymViewApp', '0005_remove_exercises_weeks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedtrainings',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='training',
            name='exercises',
        ),
        migrations.AddField(
            model_name='exercises',
            name='training',
            field=models.ManyToManyField(to='gymViewApp.training'),
        ),
    ]
