# Generated by Django 4.2.7 on 2023-11-20 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymViewApp', '0006_remove_savedtrainings_exercises_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercises',
            name='training',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='exercises',
        ),
        migrations.AddField(
            model_name='exercises',
            name='exercises',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gymViewApp.weight'),
        ),
        migrations.AddField(
            model_name='savedtrainings',
            name='exercises',
            field=models.ManyToManyField(to='gymViewApp.exercises'),
        ),
        migrations.AddField(
            model_name='training',
            name='exercises',
            field=models.ManyToManyField(to='gymViewApp.exercises'),
        ),
    ]
